### ISSUE TITLE
Separate out logging or make URL trigger optional

### ISSUE THREAD

**Issue by micschk** [lekoala/silverstripe-simple-jobs#2]
Thanks for this nice module. While I like the simplicity of having recurring jobs triggered from an external URL, this also imposes some limits (I think). For example the maximum allowed time spent handling a request is usually 30-60 seconds, after which the process times out. Also adds a dependency on an external system, of course. 

Hence it might be interesting to make the URL-triggering optional and also facilitate direct cron-based triggering. What you'd gain compared to the regular crontask module, is visibility of the results in the database (a crucial plus, if you ask me).

Another option might be to separate out the result-logging into its own module which could then be added onto the regular crontask module as well? Not sure if which route would be best (if at all interested).

Oh, you might be interested in my [silverstripe-cronkeep module which adds a web-based crontask editing interface](https://github.com/restruct/silverstripe-cronkeep).

**Comment by lekoala** [comment]
Hi, thanks for your feedback!

This module is indeed not made to handle large tasks (hence simple), although I was thinking of adding a way to run only one task per call instead of calling all of them (while it could introduce a slight delay, it could limit the amount of potential problems).
What I like in not using cron itself it that I don't have to care if the server is properly configured to run cron tasks (some servers use anacron for instance), which php interpreter is going to be used (for servers with multiple php version for instance), having to flush / dev/build the cli manifest... 

I agree with your argument about adding an external service, but most of the time, I use it anyway for monitoring uptime. It's also really easy to setup your own triggers using "real" cron jobs.
You can also already use regular cron jobs against the simple-jobs/trigger url, I've updated the documentation accordingly.
